### ISSUE TITLE
Loading a dump doesn't work with Neo4j 4.4.2

### ISSUE THREAD

**Issue by StrangeTcy** [neo4j-graph-examples/icij-paradise-papers#13]
Trying to restore a database from a `icij-paradise-papers-43.dump` with a neo4j v 4.4.2 leads to a following error:
`org.neo4j.cli.CommandFailedException: Not a valid Neo4j archive: `, which boils down to a 
```
Suppressed: java.util.zip.ZipException: Not in GZIP format
                at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:166)
                at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
                at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
                at org.neo4j.dbms.archive.StandardCompressionFormat$1.decompress(StandardCompressionFormat.java:52)
                at org.neo4j.dbms.archive.StandardCompressionFormat.decompress(StandardCompressionFormat.java:145)
                at org.neo4j.dbms.archive.StandardCompressionFormat.decompress(StandardCompressionFormat.java:129)
                ... 18 more
```
The `dbms.allow_upgrade=true` is uncommented in my neo4j.conf

Am I doing anything wrong?

**Comment by jexp** [comment]
Did you install git lfs before cloning the repo? Check that it’s 500mb not 132 bytes large. 
Or you need to download it manually.
